version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Adjust based on your project requirements
    commands:
      - echo Installing Python dependencies
      - pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo Running Python build
      - python build_script.py  # Replace with your Python build script

  post_build:
    commands:
      - echo Post-build phase
      - mkdir -p build_output
      - cp -r output_files/* build_output/  # Adjust to match your Python build outputs

artifacts:
  files:
    - '**/*'
    - 'build_output/**/*'

cache:
  paths:
    - '.cache/pip/**/*'  # Cache Python dependencies
