version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Default Python version; adjust as needed
    commands:
      - echo Installing default dependencies
      - pip install --upgrade pip
      - pip install boto3  # Example of a default dependency, remove if unnecessary

  build:
    commands:
      - echo Running default Python build
      - mkdir -p build_output
      - echo "Hello, CodeBuild!" > build_output/output.txt

artifacts:
  files:
    - '**/*'
    - 'build_output/**/*'
