version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  
    commands:
      - echo Installing default dependencies
      - pip install --upgrade pip
      - pip install boto3  

  build:
    commands:
      - echo Running default Python build
      - mkdir -p build_output
      - echo "Dev CodeBuld WORKS!" > build_output/output.txt

artifacts:
  files:
    - '**/*'
    - 'build_output/**/*'